[project]
authors = ["darrenkjr <darren.rajit@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "evidence_retrieval"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
pandas = "*"
jupyterlab = ">=4.3.5,<5"
jupyter = ">=1.1.1,<2"
upsetplot = ">=0.9.0,<0.10"
matplotlib = ">=3.10.0,<4"
aiohttp = ">=3.11.11,<4"
aiolimiter = ">=1.2.1,<2"
python-dotenv = ">=1.0.1,<2"
fuzzywuzzy = ">=0.18.0,<0.19"

[pypi-dependencies]
metapub = ">=0.5.12, <0.6"
rispy = ">=0.9.0, <0.10"
