# Assessing the Feasibility of Automated Single Database Searches (PubMed, Embase, OpenAlex and Semantic Scholar) for Living Guideline Maintenance and Evidence Surveillance 


## Introduction 

* Evidence Based Guidelines (EBGs) are crucial in pragmatising both Evidence Based Medicine and Person Centred Medicine within Learning Healtb Systems (LHS) by ensuring stakeholder priorities are aligned with downstream evidence synthesis. 
* This results in recommendations that are more likely to be of practical relevance to both frontline healthcare practitioners and consumers 
* Thus, the transition of EBGs towards a living format, where the available reserach evidence is continuously synthesised as it is produced;  is paramount to ensuring that recommendations and guidance remain relevant to frontline care. 
* This is further crucial in realising high functioning and transformative learning health systems that are able to efficiently leverage the research evidence as it is produced. 
* However, the production of EBGs is highly time-consuming and expensive. Transition towards a living format utilising current (mostly manual) approaches compounds this, and ongoing maintenance could be potentially cost-prohibitive.
* As such,  both automation and aritficial intelligence enabled methods have a clear role to play towards enabling the goal of living, continually relevant guidelines. 
* Thus, the first step in transitioning EBGs towards a living format firsty requires a method to continuously monitor and retrieve the current state of the literature, prior to downsteram screening, data extraction and meta analysis.
* The past 5 years have seen the rise of bibliographic databases that allow for progammatic (and by extension, automated) access to research evidence through applicaftion programming interfaces (API). 
* However, limited work has been done in understanding the extent of coverage of such databases, and whether focusing search or evidence retrieval efforts on a single bibliographic database is sufficient for the purposes of continually searching the literature, and triggering updates when relevant. Indeed the Austrlaian Living Strple Guidelines recently transitioned to such an approach, only searching PubMed for updates after uncovering that X % of articles could be retrieved from PubMed alone. 
* As such, we build on our prior work developing the 2023 Edition of the International PCOS Guidelines by beginning the transition of the guidelines to a living format. The first step being understanding the extent of the coverage of this new generation of databases, and whether a single database search would be sufficient for evidence surveillanec purposes, thus allowing savings in terms of effort. 
* Here the assumption is that favourable coverage of articles included in the current edition of the guidelines would predict favourable coverage of potentially relevant articles in the future. 
* The International PCOS Guidelines involved the production of X evidence reviews, across 5 themes or Guideline Developmenbt Groups (GDGs). 
* XX of these evidence reviews were systematic review updates, XX were new systematic reviews, and a further X were narrative reviews. Here we tested coverage of articles that were included in both the systematic review updates and new systematic reviews that were carried out in the guidelines. 
* 4 databases were tested. Firstly, PubMed and Embase, comprising the 2 most common databases that were searched. Secondly, OpenAlex and Semantic Scholar, which represent the new generation of field agnostic, bibliographic databases that i) aggregate multiple sources ii) and allow for programmatic access to the research corpora via publically avaialble APIs. All databases were also chosen on the basis of API availability that would enable automated and programmatic access to the research evidence.


## Aims 

* To evaluate the coverage and feasibility of using only PubMed, Embase, OpenAlex or Semantic Scholar in programmatically retrieving articles that were included in the 2023 Edition of the International PCOS Guidelines. 

## Methods 

Code and data required to replicate the retrieval process and subsequent analyses is available as a public GitHub repository : XXX

1. Articles that were included after full text screening for each evidence review conducted as part of the 2023 International PCOS Guideline, were extracted from the technical report of the guidelines. 
2. The Digital Object Identifier (DOI) of each included article was then retrieved for each article. Where DOIs were not retreivable, PubMed IDs were retrieved instead. If this failed, then the title of the article was extracted.
3. DOIs and PubMed IDs were then used to programmatically retrieve article metadata from the PubMed, OpenAlex, and Semantic Scholar APIs respectively to confirm coverage.  
4. As the Embase API required an additional subscription for access, searching within Embase was instead conducted via the Ovid interface.
5. A second round, title only search was then conducted for all databases in instances where retrieval by DOI or PMID failed, or if a DOI or PMID was not retrievable for a particular article. 
6. Article metadata was then consolidated for each database and the extent of coverage for each database was then evaluated. 
7. The exstent of overlap across each database was also evaluated 
8. An exploratory sensitivity analysis of articles that were not retrievable for each database was also conducted via extracting the risk of bias assessment that was conducted for each non-retrievable article as part of the 2023 International PCOS Guideline. This is then presented as a proportion by database. 


## Results 

A total of X articles were included in the international PCOS guidelines across all systematic reviews and systematic review updates. Table X below depicts the extent of coverage of databases that were tested. OpenAlex had the best coverage, followed by Semantic Scholar, Embase, and then PubMed. 

tABLE X: 

Figure X Placeholder: TopSet Diagram graphically depicting overlap across each databadse 

Figure X Placeholder  : graph depicting percentage of low, medium, high risk of bias of artricles that were missed by each deatabase. 


## Discussion 

* Summary of results. Note that Embase API was planned to be used, however an institutional subscription was required, and due to time constraints, evaluation proceeded without waiting for API access to be granted. Thus, Embase was searched via Ovid Medline instead. Nonetheless, the other 3 options have publically avaialble APIs that are accessible free of charge for reserach / academic purposes. Thus these are recommended for surveillance purposes. 

* Placeholder - get co-authors first reaction 

### Limitations 


### Future wprk 

* Reverse engineer a high sensitivity search strategy for best performing database. However, we expect that such approaches would result in low specificity (or precision). Thus such search strategies should be integrated with supplementary approaches to improve efficiencyby constraining the articles required to be screened by a human. We leave this for planned future work. (DOI Protocol)

## Conclusion 